# Your Website Title
title: Welcome to your dream !

# Your Website URL
url: 'https://github.com/Yanjiuruhou/Yanjiuruhou.git'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Yanjiuruhou
tagline: Software Developer, IoT, Reverse Engineering
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Full Stack Developer, IoT, Reverse Engineering
description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: 1101457203@qq.com
website: Yanjiuruhou.github.io # do not add http://
linkedin: realmelvinchng
github: Yanjiuruhou

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm